obstacle_range: 1.0
raytrace_range: 5.0
robot_radius: 0.22
inflation_radius: 0.05
max_obstacle_height: 0.6
min_obstacle_height: 0.0
observation_sources: scan
scan: {data_type: LaserScan, topic: /scan, marking: true, clearing: true, expected_update_rate: 0}
